# Generated by Django 4.2.19 on 2025-03-06 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_vault', '0002_snippet_user_alter_snippet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
